library(utils)
require(mw3dlib)
library(devtools)
detach(package:mw3dlib)
remove.packages(c("mw3dlib"))

#curwd <- getwd()
#setwd("f:/88acres/5-packages/")
devtools::document("mw3dlib")
install.packages("mw3dlib",type = "source",repo = NULL,verbose = T)
#setwd(curwd)
