library(mw3dlib)
context("readCompObjCrazyfile")

test_that("rgbToStringColor works", {
  robj <- readCompObjCrazyflie()
  expect_equal(is.null(robj),FALSE)
  expect_equal(is.null(robj$cdf),FALSE)
  expect_equal(is.null(robj$pdf),FALSE)
  expect_equal(is.null(robj$ptdf),FALSE)
  expect_equal(is.null(robj$vidf),FALSE)
  expect_is(robj$cdf,"data.frame")
  expect_is(robj$pdf,"data.frame")
  expect_is(robj$ptdf,"data.frame")
  expect_is(robj$vidf,"data.frame")
  expect_equal(nrow(robj$cdf),17)
  expect_equal(nrow(robj$pdf),8)
  expect_equal(nrow(robj$ptdf),11653)
  expect_equal(nrow(robj$vidf),22572)
})